"""Add date column to transactions

Revision ID: ed90e5dcc09a
Revises: 1ca61248c55a
Create Date: 2026-07-10 11:35:13.152580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed90e5dcc09a'
down_revision: Union[str, Sequence[str], None] = '1ca61248c55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'transactions',
        sa.Column(
            'date',
            sa.Date(),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
